PD.settings = PD.settings || {}

PD.settings.homology = {
  'A':          ['GTATTTTCAGGGCGCC',         'GACGGAGCTCGAATTTCA'],
  'B (His)':    ['AGGAGATATACATATG',         'GAAGTACAGGTTCTC'],
  'B (no His)': ['AGGAGATATACATATG',         'GAAGTACAGGTTCTCTCA'],
  'C':          ['TACTTCCAATCCATG',          'TATCCACCTTTACTGTCA'],
  'D (w/ TEV)': ['GTATTTTCAGGGCGCC',         'GTCGACTGCAGAATTtca'],
  'E (no TEV)': ['TCCGGACTCAGATCT',          'GTCGACTGCAGAATTtca'],
  'F':          ['CGAAACGAGGAATTCTCGATG',    'CAGGTTCTCACTAGT'],
  'G':          ['GCTCGAGAATTCTTCG',         'CAGGTTCTCACTAGT'],
  'H':          ['TACGTAGAATTCTCGATG',       'CAGGTTCTCACTAGT'],
  'I':          ['TACGTAGAATTCTCG',          'CAGGTTCTCACTAGT'],
  'J (w/ TEV)': ['GTATTTTCAGGGCGCC',         'CAATGCCAATAGGATATCtca'], 
  'K (no TEV)': ['TCCGGACTCAGATCT',          'GTGGTGGTGGTGCTCGAGtca'],
  '72':         ['CATCATTTTGGCAAAGAATTCATG', 'GGAGGGAGAGGGGCGGAATTCtca'],
  '73':         ['ACCTGTGGGTACCCGCTCGAGATG', 'TATCGATACCGTCGACCTCGAGtca'],
  '74':         ['TCTGCTACCACAGCCGCGGATCC',  'TCCTTCACAAAGATCCTCTAGAtca'],
  '76':         ['CATCATCAGACCACGCGGATTC',   'TCCTTCACAAAGATCCTCTAGAtca'],
}

PD.settings.homology_length = 7 // amino acids
PD.settings.min_construct_length = (PD.settings.homology_length * 2) - 1

PD.settings.vectors = {
  'pLEICS-01':       '{His*6}-SSGVDLGT-{TEV site 1}',
  'pLEICS-02':       '{GST}-SS-{TEV site 1}',
  'pLEICS-03':       '{His*6}-SSGVDLGT-{TEV site 1}',
  'pLEICS-04':       '{GST}-SS-{TEV site 1}',
  'pLEICS-05':       '{TEV site 1}-LE-{His*6}',
  'pLEICS-06 (1st)': '{His*6}-SSGVDLGT-{TEV site 1}',
  'pLEICS-06 (2nd)': '{TEV site 1}-LE-{His*6}-LESG-{S}-STSAA',
  'pLEICS-07':       '{His*6}-SSGLVPRGSGM-{S}-PDLGTGS-{TEV site 2}',
  'pLEICS-08':       '{GST}-DGSTSGSG-{His*6}-SAGLVPRGSTAIGM-{S}-PDLGTGS-{TEV site 2}',
  'pLEICS-09':       '{Trx}-GSGSGHM-{His*6}-SSGLVPRGSGM-{S}-PDLGTGS-{TEV site 2}',
  'pLEICS-10':       '{MBP}-SNNNNNNNNNNLG-{TEV site 2}',
  'pLEICS-11':       '{His*6}-DYDIPTT-{TEV site 2}',
  'pLEICS-12':       '{His*10}-{Flag*3}-GS-{TEV site 2}',
  'pLEICS-13':       '{His*10}-{Flag*3}-GS-{TEV site 2}',
  'pLEICS-14':       '{GST}-GS-{TEV site 2}',
  'pLEICS-15':       '{TAP}-CPGGS-{TEV site 2}',
  'pLEICS-16':       '{GST}-DLVPRGS-{TEV site 2}',
  'pLEICS-17':       '{GST}-GSTSGGGGSNNNPPTPTPSSGSG-{His*6}-SAALEVLFQGPGYQDP-{TEV site 2}',
  'pLEICS-18':       '{MBP}-SNNNNNNNNNNPMS-{TEV site 2}',
  'pLEICS-19':       '{HA}-LMAMEAR-{TEV site 2}',
  'pLEICS-20':       '{Myc}-LMAMEAR-{TEV site 2}',
}

PD.settings.tags = {
  'His':        'H',
  'HA':         'MYPYDVPDYA',
  'Myc':        'ASMQALISEEDL',
  'Flag':       'DYKDDDDK',
  'GST':        'MSPILGYWKIKGLVQPTRLLLEYLEEKYEEHLYERDEGDKWRNKKFELGLEFPNLPYYIDGDVKLTQSMAIIRYIADKHNMLGGCPKERAEISMLEGAVLDIRYGVSRIAYSKDFETLKVDFLSKLPEMLKMFEDRLCHKTYLNGDHVTHPDFMLYDALDVVLYMDPMCLDAFPKLVCFKKRIEAIPQIDKYLKSSKYIAWPLQGWQATFGGGDHPPKS',
  'S':          'KETAAAKFERQHMDS',
  'Trx':        'MSDKIIHLTDDSFDTDVLKADGAILVDFWAEWCGPCKMIAPILDEIADEYQGKLTVAKLNIDQNPGTAPKYGIRGIPTLLLFKNGEVAATKVGALSKGQLKEFLDANLA',
  'TAP':        'KRRWKKNFIAVSAANRFKKISSSGALGSGSGTMDEKTTGWRGGHVVEGLAGELEQLRARLEHHPQGQREPSGGCKLG',
  'MBP':        'MKTEEGKLVIWINGDKGYNGLAEVGKKFEKDTGIKVTVEHPDKLEEKFPQVAATGDGPDIIFWAHDRFGGYAQSGLLAEITPDKAFQDKLYPFTWDAVRYNGKLIAYPIAVEALSLIYNKDLLPNPPKTWEEIPALDKELKAKGKSALMFNLQEPYFTWPLIAADGGYAFKYENGKYDIKDVGVDNAGAKAGLTFLVDLIKNKHMNADTDYSIAEAAFNKGETAMTINGPWAWSNIDTSKVNYGVTVLPTFKGQPSKPFVGVLSAGINAASPNKELAKEFLENYLLTDEGLEAVNKDKPLGAVALKSYEEELAKDPRIAATMENAQKGEIMPNIPQMSAFWYAVRTAVINAASGRQTVDEALKDAQTNSS',
  'TEV site 1': 'ENLYFQS',
  'TEV site 2': 'ENLYFQGA',
}